name: "Run unit tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  # Access to your repository.
  contents: read
  # Access to pull request. The `write` access if you the `comment` is enabled
  # within the action, otherwise can be `read`.
  pull-requests: write
  # Access to pull request statuses. The `write` access if you the `check` is enabled
  # within the action, otherwise can be `read`.
  statuses: write

jobs:
  test:
    name: "Test on PHP ${{ matrix.php }} (guzzle ${{ matrix.guzzle-version }}, money ${{ matrix.money-version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'

        guzzle-version:
          - '6.0'
          - '7.0'

        money-version:
          - '3.0'
          - '4.0'

        include:
          - php: '8.1'
            guzzle-version: '7.0'
            money-version: '4.0'
            main: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: xdebug
          tools: php-parallel-lint/php-parallel-lint

      - name: Lint PHP code
        run: parallel-lint .

      - name: Pin dependency versions
        run: |
          composer require \
            --no-update \
            guzzlehttp/guzzle:^${{ matrix.guzzle-version }} \
            moneyphp/money:^${{ matrix.money-version }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--ignore-platform-req=php"

      - name: Validate formatting
        run: composer run format -- --dry-run
        if: matrix.main

      - name: Run tests
        run: composer run test-coverage

      - name: Determine coverage
        uses: slavcodev/coverage-monitor-action@v1
        if: matrix.main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: coverage/clover.xml
          threshold_alert: 75
          threshold_warning: 95
